name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "429e4817165c49a4873cf8a012d97641" }
]

[triggers]
crons = [ ]
