name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@2.2.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
          configFile: wrangler.toml
